[ -f ~/app/data/.bash_profile ] && source ~/app/data/.bash_profile

if [ -z "$PS1" ]; then
    return
fi

for d in ~/*; do
    [ -f $d/bin/bash_profile ] && source $d/bin/bash_profile
done

export PS1="[$CLOUDWAY_APP_DNS \W] "
export TMOUT=300
export SHELL=/bin/bash

# unidle the container
[ -f ~/app/.state -a $(< ~/app/.state) == 'IDLE' ] && cwctl start > /dev/null
