#!/bin/bash
#
# This shell script starts Cloudway workers
#
# chkconfig: 345 90 01
#
# description: Start Cloudway workers

case "$1" in
  start)
    /usr/share/cloudway/libexec/cwadminctl.sh startall
    ;;
  stop)
    /usr/share/cloudway/libexec/cwadminctl.sh stopall
    ;;
  restart|force-restart)
    /usr/share/cloudway/libexec/cwadminctl.sh restartall
    ;;
  reload)
    ;;
  staus)
    # TODO
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac

exit $?
